AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Template

Parameters:
  NotificationEmail:
    Type: String
    
Resources:
# -----------------------
# VPC
# -----------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: aws-study-vpc

# -----------------------
# Subnets
# -----------------------
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24 
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true 
      Tags:
        - Key: Name
          Value: PublicSubnetA

  PublicSubnetC: 
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true 
      Tags:
        - Key: Name
          Value: PublicSubnetC

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: false 
      Tags:
        - Key: Name
          Value: PrivateSubnetA

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: false 
      Tags:
        - Key: Name
          Value: PrivateSubnetC

# -----------------------
# Internet Gateway
# ------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-igw

# -----------------------
# VPC Gateway Attachment
# -----------------------
  AttachGateway: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
      

# -----------------------
# Route Table (Public)
# -----------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: aws-study-route

# -----------------------
# Route (Public)
# -----------------------
  PublicRoute:

    Type: AWS::EC2::Route
    DependsOn: AttachGateway 
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref InternetGateway
      
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation 
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

# -----------------------
# Security Group 
# -----------------------
  EC2SecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: AWS Study EC2
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ELBSecurityGroup 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-ec2-sg     

  RDSSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study RDS
      VpcId: !Ref VPC
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-rds-sg

# -----------------------
# EC2 
# -----------------------

  EC2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Sub "resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64" 
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetA
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
      Monitoring: false
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-ec2  
      IamInstanceProfile: !Ref EC2InstanceProfile

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DBSecret
      
  EC2InstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
        - !Ref EC2Role
      
# -----------------------
# ELB
# -----------------------
  ELB: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-elb
      Scheme: internet-facing 
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetC
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-elb

  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Protocol: HTTP
      Port: 8080
      VpcId: !Ref VPC
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      Tags: 
        - Key: Name
          Value: aws-study-elb-target-group
      Targets: 
        - Id: !Ref EC2
          Port: 8080

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ELB 
      DefaultActions:
        - Type: forward 
          TargetGroupArn: !Ref ELBTargetGroup 
      Port: 80
      Protocol: HTTP 
  
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref VPC 
      GroupDescription: ELB SG 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      
# -----------------------
# RDS
# ----------------------- 
  RDS:
    Type: AWS::RDS::DBInstance 
    Properties: 
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t4g.micro 
      Port: 3306
      StorageType: gp2
      BackupRetentionPeriod: 1
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}::password}}'
      DBName: mydb
      Engine: mysql 
      EngineVersion: "8.0.41"
      LicenseModel: general-public-license
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: mydb 

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: mydb-secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}' 
        GenerateStringKey: "password" 
        PasswordLength: 16 
        ExcludeCharacters: '"@/\ ' 

  DBSubnetGroup:  
    Type: AWS::RDS::DBSubnetGroup 
    Properties: 
      DBSubnetGroupDescription: DB Subnet Group 
      SubnetIds: 
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetC
      Tags:
        - Key: Name
          Value: aws-study-db-subnet-group

# -----------------------
# AWS WAF 
# -----------------------
  WebACL: 
    Type: AWS::WAFv2::WebACL 
    Properties: 
      Name: !Sub "${AWS::StackName}-web-acl" 
      Scope: REGIONAL 
       
      DefaultAction: 
        Allow: {}
      
      VisibilityConfig: 
        SampledRequestsEnabled: true 
        CloudWatchMetricsEnabled: true
        MetricName: WebACLMetric 

      Rules: 
        - Name: BlockTestURI
          Priority: 0 

          Action: 
            Block: {}
          
          Statement: 
            ByteMatchStatement: 
              SearchString: "/block-test" 

              FieldToMatch: 
                UriPath: {} 

              TextTransformations: 
                - Priority: 0
                  Type: NONE   
              
              PositionalConstraint: CONTAINS 

          VisibilityConfig: 
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true
            MetricName: BlockTestURIMetric

        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1 

          OverrideAction: 
            None: {} 

          Statement: 
            ManagedRuleGroupStatement: 
              VendorName: AWS 
              Name: AWSManagedRulesCommonRuleSet

          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSetMetric 

# -----------------------
# WAF WebACL Association
# -----------------------         
  WebACLAssociation: 
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !GetAtt ELB.LoadBalancerArn
      WebACLArn: !GetAtt WebACL.Arn 

# -----------------------
# WAF Logging Configuration
# -----------------------
  WAFLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt WebACL.Arn
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn 
      
# -----------------------
# CloudWatch Logs
# -----------------------
  WAFLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "aws-waf-logs-${AWS::StackName}" 
      RetentionInDays: 14 
       
# -----------------------
# SNSTopic
# -----------------------
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

# -----------------------
# CloudWatch Alarm
# -----------------------
  EC2CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmName: !Sub "${AWS::StackName}-ec2-cpu-alarm"
      AlarmDescription: "Aws-study EC2のCPU使用率が 70%以上になりました。"

      Namespace: "AWS/EC2"
      Dimensions: 
        - Name: "InstanceId"
          Value: !Ref EC2 
      MetricName: "CPUUtilization"
      Unit: "Percent"

      Period: 300 
      Statistic: "Average" 
      
      Threshold: 70
      ComparisonOperator: "GreaterThanOrEqualToThreshold" 
      EvaluationPeriods: 3 
      DatapointsToAlarm: 2 
      TreatMissingData: "notBreaching"

      ActionsEnabled: True 
      AlarmActions: 
        - !Ref SNSTopic

  ELB5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-elb-5xx-alarm"

      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count

      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt ELB.LoadBalancerFullName

      Statistic: Sum
      Period: 300

      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold

      EvaluationPeriods: 1
      TreatMissingData: "notBreaching"
      AlarmActions:
        - !Ref SNSTopic   

  WAFBlockedRequestsAlarm: 
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-waf-blocked-requests" 

      AlarmDescription: "WAF Blocked requests detected" 

      Namespace: AWS/WAFV2
      MetricName: BlockedRequests
      
      Dimensions: 
        - Name: WebACL 
          Value: !Sub "${AWS::StackName}-web-acl" 
          
        - Name: Rule
          Value: ALL

        - Name: Region
          Value: !Ref 'AWS::Region'

      Statistic: Sum 
      Period: 300 
       
      EvaluationPeriods: 1 
      Threshold: 1 
      ComparisonOperator: GreaterThanOrEqualToThreshold 
       
      TreatMissingData: "notBreaching" 
      AlarmActions: 
        - !Ref SNSTopic 
